### ISSUE TITLE
{"redirect_uri": ["Not a well formed URL."]} at Discord api

### ISSUE THREAD

**Issue by momochqn** [KanekiWeb/Xenos#18]
I got the website run and all the stuff but when im trying to login with discord i get this:
`{"redirect_uri": ["Not a well formed URL."]}`

**Comment by GarudaID** [comment]
> 

same problem

**Comment by FULCOS** [comment]
Add https:// in front of your website

**Comment by alerey1610** [comment]
> Add https:// in front of your website

ty this worked in some way but now im having an problem with the redirected site i always have to put .php behind yoursite.com/login(.php) because it always redirects me to none php sites and i think that this gives me a problem now cuz it cant reach any site after redirecting me i already tried putting .php everywhere
